[book]
authors = ["The RayCanary Team"]
language = "en"
src = "doc"
title = "RayCanary - An IMSI Catcher Catcher"

[output.html]
edit-url-template = "https://github.com/GreerBK/raycanary/edit/main/{path}"
additional-css = ["doc/custom.css"]
