#!/bin/sh

# Tool to cross-compile outside of Linux.
#
# On MacOS, OrbStack is recommended, but other docker distributions will work
# too.
#
# Usage:
# ./tools/run-docker-devenv
#
# Inside the shell:
# cargo build --bin raycanary-daemon --target armv7-unknown-linux-musleabihf --release
#
# Your output binary is in ./target/armv7-unknown-linux-musleabihf/release/raycanary-daemon

docker build -t raycanary-devenv -f tools/devenv.dockerfile .
exec docker run --user $UID:$GID -v ./:/workdir -w /workdir -it raycanary-devenv "$@"
